const BRIDGE_SIZE_MIN_RANGE = 3;
const BRIDGE_SIZE_MAX_RANGE = 20;
const DOWNSIDE_SYMBOL_NUM = 0;
const DOWNSIDE_SYMBOL = 'D';
const UPSIDE_SYMBOL = 'U';

module.exports = {
  BRIDGE_SIZE_MIN_RANGE,
  BRIDGE_SIZE_MAX_RANGE,
  DOWNSIDE_SYMBOL_NUM,
  DOWNSIDE_SYMBOL,
  UPSIDE_SYMBOL,
};
