const INPUT_CHAR_LENGTH = 1;
const AVAILABLE_INPUT_ARRAY = ["U", "D"];
const AVAILABLE_RETRY_QUIT_ARRAY = ["R", "Q"];
const UP = "U";
const DOWN = "D";
const RETRY = "R";
const QUIT = "Q";
const FAIL = "실패";
const SUCCESS = "성공";
module.exports = {
  INPUT_CHAR_LENGTH: INPUT_CHAR_LENGTH,
  AVAILABLE_INPUT_ARRAY: AVAILABLE_INPUT_ARRAY,
  AVAILABLE_RETRY_QUIT_ARRAY: AVAILABLE_RETRY_QUIT_ARRAY,
  RETRY: RETRY,
  QUIT: QUIT,
  UP: UP,
  DOWN: DOWN,
  FAIL: FAIL,
  SUCCESS: SUCCESS,
};
