const INPUT_CHAR_LENGTH = 1;
const AVAILABLE_INPUT_ARRAY = ["U", "D"];
const AVAILABLE_RETRY_QUIT_ARRAY = ["R", "Q"];
module.exports = {
  INPUT_CHAR_LENGTH: INPUT_CHAR_LENGTH,
  AVAILABLE_INPUT_ARRAY: AVAILABLE_INPUT_ARRAY,
  AVAILABLE_RETRY_QUIT_ARRAY: AVAILABLE_RETRY_QUIT_ARRAY,
};
