const Constant = {
  BLANK_STRING: " ",
  CORRECT_STRING: "O",
  FAIL_STRING: "X",
  COMMAND_UP_DIRECTION_STRING: "U",
  COMMAND_DOWN_DIRECTION_STRING: "D",
  COMMAND_QUIT_STRING: "Q",
  COMMAND_RETRY_STRING: "R",
};

module.exports = Constant;
